// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHkMfwLvAZag8OkVGvQm23Aic0JSD_Og8',
    appId: '1:148473932951:android:7322e6b04980d5751d4dd2',
    messagingSenderId: '148473932951',
    projectId: 'towhid-portfolio',
    databaseURL: 'https://towhid-portfolio.firebaseio.com',
    storageBucket: 'towhid-portfolio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyEnTMP1Ori8IDC7bfgqYxhQCHXzWdP4A',
    appId: '1:148473932951:ios:c893f98a39578fae1d4dd2',
    messagingSenderId: '148473932951',
    projectId: 'towhid-portfolio',
    databaseURL: 'https://towhid-portfolio.firebaseio.com',
    storageBucket: 'towhid-portfolio.appspot.com',
    androidClientId: '148473932951-6f96i10e1if2huq6b8ofgcak4eknik4p.apps.googleusercontent.com',
    iosClientId: '148473932951-pgofl3dkmfqmv3mrmmgqq48d1um1391f.apps.googleusercontent.com',
    iosBundleId: 'itstowhid.com.carWorkshop',
  );
}
